### ISSUE TITLE
documentation - after installing lxdhub in lxd locally how can I add my local images to it?

### ISSUE THREAD

**Issue by bmullan** [Roche/lxdhub#37]
Ubuntu 18.04 w/SNAP LXD

I have about 20 images on my machine locally.   I must be missing something but how can I add my local images to the now local LXDHub?

I installed lxd-hub into a local LXD container named ciab-lxdhub.

In the web interface I don't see any button/tab/etc like an "image import" to do this, and I'm not sure if/how lxdhub can have local images copied to it using the LXD cli and **lxc copy**  or **lxc publish**

How would/should this be done?

**Comment by erickeller** [comment]
@bmullan thanks for the heads up and sorry for the late response.

Of course you can do this relatively easy.
All LXDHub remotes are defined in the lxdhub/lxdhub.yml file in the image you downloaded.

so if you followed the steps:
```
lxc remote add lxdhub https://lxdhub.xyz:8443 --accept-certificate --public
lxc launch lxdhub:lxdhub mylxdhub
# customize with an additional repository name efiks
# workaround if you do not have the latest version...
lxc exec mylxdhub -- chown lxdhub:users /var/lib/lxdhub/lxdhub/lxdhub.yml
lxc exec mylxdhub -- su -l lxdhub -c "cat << EOF >> ~/lxdhub/lxdhub.yml
  - name: efiks
    url: https://images.efiks.ovh:8443
    protocol: lxd
    public: true
    readonly: true
EOF"
# restart services
lxc exec mylxdhub -- systemctl restart lxdhub-dbsync.service
lxc exec mylxdhub -- systemctl restart lxdhub.service
```
You will be able to see a new efiks remote in the drop down with the appropriate images

**Comment by bmullan** [comment]
@erickeller - thanks for the update & instructions... I'll give it a try.
