### ISSUE TITLE
missing lxdhub version in frontend

### ISSUE THREAD

**Issue by erickeller** [Roche/lxdhub#44]
Currently it's difficult to notice which version of lxdhub is deployed.
There is no indication of the web front end.

would be nice to add the information like git branch/hash or tag...

**Comment by BrunnerLivio** [comment]
Package version (equal to git version) will get displayed in footer.

![Selection_052](https://user-images.githubusercontent.com/9899423/60724584-1c666100-9f37-11e9-8465-45714923524d.png)
